#!/usr/bin/env python3
"""Generate the COM vtable slot table for the CLR profiling API.

The profiler object has to expose a vtable whose layout matches
ICorProfilerCallback11 exactly, and it calls back into ICorProfilerInfo12 the
same way. Getting a slot index wrong neither fails to build nor fails to load:
the runtime simply calls the wrong function pointer. So the indices are not
written by hand - they are derived from the interface declarations that the
runtime itself ships, and the result is committed as a generated header.

Usage (from src/Native/clrprofiler):
    python3 tools/gen_corprof_slots.py > include/CorProfSlots.h
    python3 tools/gen_corprof_slots.py --check include/CorProfSlots.h
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request

# Pinned: the vtable layout is append-only across runtime versions, but pinning
# makes regeneration reproducible and says which runtime the table was read from.
RUNTIME_TAG = "v10.0.0"
CORPROF_URL = (
    "https://raw.githubusercontent.com/dotnet/runtime/"
    f"{RUNTIME_TAG}/src/coreclr/pal/prebuilt/inc/corprof.h"
)
# Metadata, for turning a FunctionID into a name. Hand-written rather than MIDL output, so it is
# declared with a different set of macros and needs its own parser.
COR_URL = f"https://raw.githubusercontent.com/dotnet/runtime/{RUNTIME_TAG}/src/coreclr/inc/cor.h"

# Every interface derives from the one before it, so the flattened vtable is
# IUnknown's three slots followed by each interface's own methods in order.
CALLBACK_CHAIN = [f"ICorProfilerCallback{n}" for n in ["", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11"]]
INFO_CHAIN = [f"ICorProfilerInfo{n}" for n in ["", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12"]]

IUNKNOWN_METHODS = ["QueryInterface", "AddRef", "Release"]

INTERFACE_RE = re.compile(r'MIDL_INTERFACE\("([0-9A-Fa-f-]+)"\)\s*\n\s*(\w+)\s*:\s*public\s+(\w+)')
METHOD_RE = re.compile(r"virtual\s+(?:/\*[^*]*\*/\s*)?HRESULT\s+STDMETHODCALLTYPE\s+(\w+)\s*\(")

DECLARE_RE = re.compile(r"DECLARE_INTERFACE_\(\s*(\w+)\s*,\s*(\w+)\s*\)")
STDMETHOD_RE = re.compile(r"\bSTDMETHOD(?:_\s*\(\s*[^,]+,)?\s*\(?\s*(\w+)\s*\)")
EXTERN_GUID_RE = re.compile(r"EXTERN_GUID\(\s*(\w+)\s*,([^)]*)\)")


def parse(header: str) -> dict[str, tuple[str, str, list[str]]]:
    """Map interface name -> (guid, base, ordered method names)."""
    interfaces: dict[str, tuple[str, str, list[str]]] = {}
    for match in INTERFACE_RE.finditer(header):
        guid, name, base = match.group(1), match.group(2), match.group(3)
        # The C++ declaration ends at the first closing brace at interface indent;
        # what follows is MIDL's C-style mirror of the same methods.
        end = header.index("\n    };", match.end())
        interfaces[name] = (guid, base, METHOD_RE.findall(header[match.end():end]))
    return interfaces


def parse_declared(header: str, name: str) -> tuple[str, list[str]]:
    """Ordered method names of a DECLARE_INTERFACE_ block, which is not MIDL output."""
    match = DECLARE_RE.search(header, 0)
    while match is not None and match.group(1) != name:
        match = DECLARE_RE.search(header, match.end())
    if match is None:
        raise SystemExit(f"{name} is not declared in cor.h")
    if match.group(2) != "IUnknown":
        raise SystemExit(f"{name} derives from {match.group(2)}, not IUnknown")

    end = re.compile(r"^\s*\};", re.MULTILINE).search(header, match.end())
    return match.group(2), STDMETHOD_RE.findall(header[match.end():end.start()])


def parse_guid(header: str, name: str) -> str:
    """The 11 comma-separated fields of an EXTERN_GUID, as a C initializer."""
    for match in EXTERN_GUID_RE.finditer(header):
        if match.group(1) != name:
            continue
        fields = [field.strip() for field in match.group(2).split(",")]
        if len(fields) != 11:
            raise SystemExit(f"{name} does not look like a GUID: {match.group(2)}")
        return f"{{{fields[0]}, {fields[1]}, {fields[2]}, {{{', '.join(fields[3:])}}}}}"
    raise SystemExit(f"{name} is not defined in cor.h")


def flatten(interfaces: dict[str, tuple[str, str, list[str]]], chain: list[str]) -> list[str]:
    slots = list(IUNKNOWN_METHODS)
    for index, name in enumerate(chain):
        if name not in interfaces:
            raise SystemExit(f"{name} is not declared in corprof.h")
        _, base, methods = interfaces[name]
        expected = "IUnknown" if index == 0 else chain[index - 1]
        if base != expected:
            raise SystemExit(f"{name} derives from {base}, not {expected}: the chain is not linear any more")
        slots += methods
    return slots


def emit(interfaces: dict[str, tuple[str, str, list[str]]], cor: str) -> str:
    out: list[str] = []
    out.append("// Generated by tools/gen_corprof_slots.py. Do not edit.")
    out.append(f"// Source: dotnet/runtime {RUNTIME_TAG}, src/coreclr/pal/prebuilt/inc/corprof.h")
    out.append("")
    out.append("#pragma once")
    out.append("")
    out.append('#include "CorProfAbi.h"')
    out.append("")
    out.append("namespace division::clr {")
    for label, chain in (("Callback", CALLBACK_CHAIN), ("Info", INFO_CHAIN)):
        slots = flatten(interfaces, chain)
        out.append("")
        out.append(f"/// Vtable slots of {chain[-1]}, flattened over its whole inheritance chain.")
        out.append(f"enum class {label}Slot : std::size_t {{")
        for index, name in enumerate(slots):
            out.append(f"    {name} = {index},")
        out.append(f"    SlotCount = {len(slots)},")
        out.append("};")
        out.append("")
        out.append(f"/// GUIDs of the {label.lower()} interfaces, as {{Data1, Data2, Data3, Data4[8]}}.")
        for name in chain:
            guid = interfaces[name][0].lower()
            d1, d2, d3, d4a, d4b = guid.split("-")
            bytes4 = [d4a[0:2], d4a[2:4]] + [d4b[i:i + 2] for i in range(0, 12, 2)]
            initializer = ", ".join(f"0x{b}" for b in bytes4)
            out.append(
                f"inline constexpr Guid kIid{name[1:]} = "
                f"{{0x{d1}, 0x{d2}, 0x{d3}, {{{initializer}}}}};"
            )
    # Metadata, used only to turn a method token into a name.
    _, metadata = parse_declared(cor, "IMetaDataImport")
    slots = IUNKNOWN_METHODS + metadata
    out.append("")
    out.append("/// Vtable slots of IMetaDataImport (cor.h, not MIDL output).")
    out.append("enum class MetadataSlot : std::size_t {")
    for index, name in enumerate(slots):
        out.append(f"    {name} = {index},")
    out.append(f"    SlotCount = {len(slots)},")
    out.append("};")
    out.append("")
    out.append(f"inline constexpr Guid kIidMetaDataImport = {parse_guid(cor, 'IID_IMetaDataImport')};")
    out.append("")
    out.append("}  // namespace division::clr")
    out.append("")
    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", metavar="FILE", help="compare against an existing header instead of printing")
    parser.add_argument("--header", metavar="FILE", help="read corprof.h from here instead of downloading")
    parser.add_argument("--cor-header", metavar="FILE", help="read cor.h from here instead of downloading")
    args = parser.parse_args()

    if args.header:
        with open(args.header, encoding="utf-8", errors="replace") as handle:
            source = handle.read()
    else:
        with urllib.request.urlopen(CORPROF_URL, timeout=60) as response:
            source = response.read().decode("utf-8", errors="replace")

    if args.cor_header:
        with open(args.cor_header, encoding="utf-8", errors="replace") as handle:
            cor = handle.read()
    else:
        with urllib.request.urlopen(COR_URL, timeout=60) as response:
            cor = response.read().decode("utf-8", errors="replace")

    generated = emit(parse(source), cor)

    if args.check:
        with open(args.check, encoding="utf-8") as handle:
            current = handle.read()
        if current != generated:
            print(f"{args.check} is out of date; regenerate it.", file=sys.stderr)
            return 1
        print(f"{args.check} is up to date.")
        return 0

    sys.stdout.write(generated)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
